=== simonpp64/DataWebLab_Mar2024/1.xPathPart/petit_prince_3IF.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT the_text (the_header, body)>
<!ELEMENT the_header (title, author, cover, styling_information, link+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link
          language CDATA #REQUIRED>
<!ELEMENT cover EMPTY>
<!ATTLIST cover
          path CDATA #REQUIRED>
<!ELEMENT styling_information (styling_description, styled_by, email, date)>
<!ELEMENT styling_description (#PCDATA)>
<!ELEMENT styled_by (style_manager+, NoBinome)>
<!ELEMENT style_manager (#PCDATA)>
<!ELEMENT NoBinome (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT body (paragraph+, image, paragraph+)>
<!ELEMENT paragraph (phrase+)>
<!ATTLIST paragraph
          type CDATA #REQUIRED>
<!ELEMENT phrase (#PCDATA)>
<!ATTLIST phrase
          speaker CDATA #REQUIRED
          modality CDATA #REQUIRED
          language CDATA #REQUIRED>
<!ELEMENT image EMPTY>
<!ATTLIST image
          path CDATA #REQUIRED>

=== simonpp64/DataWebLab_Mar2024/1.xPathPart/petit_prince_3IF.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE the_text SYSTEM "petit_prince_3IF.dtd">
<!--
<?xml-stylesheet type="text/xsl" href="petit-prince.xsl"?>
-->
<the_text>
  <the_header>
    <title>LePetitPrince</title>
    <author>Antoine de Saint-Exupéry</author>
    <cover path="images/prince.png"/>
    <styling_information>
      <styling_description>Traitement d'un texte franco/hongrois avec XPath / XSLT / XQuery</styling_description>
      <styled_by>
        <style_manager>Moi</style_manager>
        <style_manager>Mon binome</style_manager>
        <NoBinome>B3100</NoBinome>
      </styled_by>
      <email>text</email>
      <date>01/05/201</date>
    </styling_information>
    <link language="francais">http://wikilivres.info/wiki/Le_Petit_Prince</link>
    <link language="hongrois">http://mek.oszk.hu/00300/00384/00384.pdf</link>
  </the_header>
  <body>
    <paragraph type="narration">
      <phrase speaker="Narrateur" modality="declarative" language="francais">J'ai ainsi vécu seul, sans personne avec qui parler véritablement, jusqu'à une panne dans le désert du Sahara, il y a six ans. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">Quelque chose s'était cassé dans mon moteur, et comme je n'avais avec moi ni mécanicien, ni passagers, je me préparai à essayer de réussir, tout seul, une réparation difficile. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">C'était pour moi une question de vie ou de mort. J'avais à peine de l'eau à boire pour huit jours. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Így éltem magányosan, anélkül, hogy igazában bárkivel is szót érthettem volna, míg egyszer, hat esztendővel ezelőtt, kényszerleszállást nem kellett végeznem a Szaharában.  </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Valami eltörött a motoromban. És mivel se gépészem nem volt, se utasom, magamnak kellett nekilátnom, hogy zöld ágra vergődjem valahogyan, és kijavítsam a súlyos hibát.</phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Élet és halál kérdése volt ez számomra.</phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Alig egy hétre való ivóvizem volt.  </phrase>
    </paragraph>
    <paragraph type="narration">
      <phrase speaker="Narrateur" modality="declarative" language="francais">Le premier soir je me suis donc endormi sur le sable à mille milles de toute terre habitée. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">J'étais bien plus isolé qu'un naufragé sur un rideau au milieu de l'océan. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">Alors vous imaginez ma surprise, au levé du jour, quand une drôle de petite voix m'a réveillé. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">Elle disait: </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Ott dőltem álomra az első este a homokon, ezermérföldnyire minden lakott helytől.</phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Elhagyatottabb voltam, mint tutaján a hajótörött az óceán közepén.</phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Elképzelhető hát, mennyire meglepődtem, amikor hajnalban egy fura kis hang ébresztett föl. Azt mondta: </phrase>
    </paragraph>
    <paragraph type="dialogue">
      <phrase speaker="LePetitPrince" modality="declarative" language="francais">S'il vous plaît... dessine-moi un mouton! </phrase>
      <phrase speaker="LePetitPrince" modality="declarative" language="hongrois">Légy szíves, rajzolj nekem egy bárányt! </phrase>
      <phrase speaker="Narrateur" modality="exclamative" language="francais">Hein! </phrase>
      <phrase speaker="Narrateur" modality="exclamative" language="hongrois">Micsoda?  </phrase>
      <phrase speaker="LePetitPrince" modality="declarative" language="francais">Dessine-moi un mouton... </phrase>
      <phrase speaker="LePetitPrince" modality="declarative" language="hongrois">Rajzolj nekem egy bárányt...  </phrase>
    </paragraph>
    <paragraph type="narration">
      <phrase speaker="Narrateur" modality="declarative" language="francais">J'ai sauté sur mes pieds comme si j'avais été frappé par la foudre. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">J'ai bien frotté mes yeux. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">J'ai bien regardé. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">Et j'ai vu un petit bonhomme tout à fait extraordinaire qui me considérait gravement. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">Voilà le meilleur portrait que, plus tard, j'ai réussi à faire de lui. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">Mais mon dessin,bien sùr, est beaucoup moins ravissant que le modèle. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">Ce n'est pas de ma faute. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">J'avais été découragé dans ma carrière de peintre par les grandes personnes, à l'age de six ans, et je n'avais rien appris à dessiner, sauf les boas fermés et les boas ouverts. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Fölugrottam, mintha villám csapott volna le mellettem. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Megdörgöltem a szememet, aztán jól kimeresztettem.</phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">És egy apró emberkét láttam, egy teljességgel rendkívüli kis emberkét, amint komoly figyelemmel szemlél.</phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Itt a legjobb kép, amit később csinálnom sikerült róla. Csakhogy az én rajzom kétségkívül sokkal kevésbé elragadó, mint amilyen a mintája volt. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Igaz, nem az én hibámból. Mert ami festői pályafutásomat illeti, attól már hatesztendős koromban elvették a kedvemet a fölnőttek, így aztán nem is tanultam meg rajzolni, kivéve a csukott meg a nyitott óriáskígyókat.  </phrase>
    </paragraph>
    <paragraph type="narration">
      <phrase speaker="Narrateur" modality="declarative" language="francais">Je regardai donc cette apparition avec des yeux tout ronds d'étonnement. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">N'oubliez pas que je me trouvais à mille milles de toute région habitée. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">Or mon petit bonhomme ne me semblait ni égaré, ni mort de fatigue, ni mort de faim, ni mort de soif, ni mort de peur. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">Il n'avait en rien l'apparence d'un enfant perdu au milieu du désert, à mille milles de toute région habitée. Quand je réussis enfin de parler, je lui dis: </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Ámulattól kerek szemmel néztem hát a különös tüneményt. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Ne feledjük el: ezer mérföldre voltam minden lakott vidéktől. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Emberkémen pedig semmi jele nem volt annak, mintha eltévedt volna, vagy halálosan fáradt, halálosan éhes, halálosan szomjas lenne, esetleg halálosan félne. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Egyáltalán nem úgy festett, mint egy szerencsétlen gyerek, aki eltévedt a sivatagban, ezermérföldnyire minden lakott helytől. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois">Mikor végre szavamra leltem, azt kérdeztem tőle:  </phrase>
    </paragraph>
    <paragraph type="dialogue">
      <phrase speaker="Narrateur" modality="interrogative" language="francais">Mais qu'est-ce que tu fais là? </phrase>
      <phrase speaker="Narrateur" modality="interrogative" language="hongrois">De hát... hogy kerülsz te ide? </phrase>
    </paragraph>
    <paragraph type="narration">
      <phrase speaker="Narrateur" modality="declarative" language="francais">Et il me répéta alors, tout doucement, comme une chose très sérieuse: </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="hongrois"> Erre szelíden, és mintha valami nagyon komoly dolgot kérne, megismételte:  </phrase>
    </paragraph>
    <paragraph type="dialogue">
      <phrase speaker="LePetitPrince" modality="declarative" language="francais">S'il vous plaît... dessine-moi un mouton... </phrase>
      <phrase speaker="LePetitPrince" modality="declarative" language="hongrois">Légy szíves, rajzolj nekem egy bárányt...  </phrase>
    </paragraph>
    <paragraph type="narration">
      <phrase speaker="Narrateur" modality="declarative" language="francais">Quand le mystère est trop impressionnant, on n'ose pas désobéir. </phrase>
      <phrase speaker="Narrateur" modality="declarative" language="francais">Aussi absurde que cela me semblaît à mille milles de tous les endroits habités et en danger de mort, je sortis de ma poche une feuille de papier et un stylographe. </phrase>
